services:
  - type: web
    name: batikverse-nusantara
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --preload
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: batikverse_db
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
